# Generated by Django 5.1 on 2026-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_company_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='venue_type',
            field=models.CharField(choices=[('Café', 'Café'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Hotel', 'Hotel'), ('Other', 'Other')], default='Café', max_length=20),
        ),
    ]
