# Generated by Django 5.1 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lead_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('demo_scheduled', 'Demo scheduled'), ('converted', 'Converted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
    ]
