# Generated by Django 5.1 on 2026-06-20 09:18

import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_categories', to='menu.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='menu.category')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('branch', 'category')},
            },
            bases=(menu.models._SameCompanyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BranchItemPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='menu.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='menu.menuitem')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.subcategory')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('branch', 'menu_item', 'category', 'sub_category')},
            },
            bases=(menu.models._SameCompanyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BranchMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='menu.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='menu.menuitem')),
            ],
            options={
                'unique_together': {('branch', 'menu_item')},
            },
            bases=(menu.models._SameCompanyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BranchSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_subcategories', to='menu.branch')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='menu.subcategory')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('branch', 'sub_category')},
            },
            bases=(menu.models._SameCompanyMixin, models.Model),
        ),
    ]
