# Generated by Django 5.1 on 2026-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_branchcategory_branchitemplacement_branchmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
    ]
