# Generated by Django 5.1 on 2026-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_orderitem_order_uniq_order_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='menu_layout',
            field=models.CharField(choices=[('baseline', 'Baseline — rail + accordion'), ('tabs', 'Top tabs + scroll-spy'), ('iconrail', 'Icon rail + chips')], default='baseline', max_length=20),
        ),
    ]
