# Generated by Django 5.1 on 2026-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_branchad'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='menu_theme',
            field=models.CharField(choices=[('saffron', 'Saffron Festival'), ('berry', 'Electric Berry'), ('juice', 'Tropical Juice')], default='saffron', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(choices=[('business', 'Business'), ('vip', 'VIP')], default='business', max_length=20),
        ),
    ]
