# Generated by Django 5.1 on 2026-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_company_menu_theme_company_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='menu_theme',
            field=models.CharField(blank=True, choices=[('saffron', 'Saffron Festival'), ('berry', 'Electric Berry'), ('juice', 'Tropical Juice')], default='', max_length=20),
        ),
    ]
