# Generated by Django 5.1 on 2026-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_branch_menu_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
