# Generated by Django 5.1 on 2026-07-18 15:34

from django.db import migrations, models


def reset_themes(apps, schema_editor):
    """Founder decision 2026-07-18: hard reset — venues re-pick from the new set."""
    Company = apps.get_model('menu', 'Company')
    Branch = apps.get_model('menu', 'Branch')
    Company.objects.update(menu_theme='eco')
    # Historical models get a plain default manager inside a real migration run;
    # the live model's default manager is tenant-scoped (fail-closed), so prefer
    # all_objects when this function is direct-called (tests).
    getattr(Branch, 'all_objects', Branch.objects).update(menu_theme='')


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_company_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='menu_theme',
            field=models.CharField(blank=True, choices=[('fastfood', 'Classic Fast Food'), ('citrus', 'Citrus Charge'), ('contrast', 'Energetic Contrast'), ('eco', 'Ecological Clean'), ('cozy', 'Gourmet Cozy'), ('herbal', 'Natural Herbal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='menu_theme',
            field=models.CharField(choices=[('fastfood', 'Classic Fast Food'), ('citrus', 'Citrus Charge'), ('contrast', 'Energetic Contrast'), ('eco', 'Ecological Clean'), ('cozy', 'Gourmet Cozy'), ('herbal', 'Natural Herbal')], default='eco', max_length=20),
        ),
        migrations.RunPython(reset_themes, migrations.RunPython.noop),
    ]
