# Generated by Django 5.1 on 2026-07-22 18:22

import django.db.models.deletion
import pgvector.django
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_guest_theme_palettes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('source', models.CharField(max_length=20)),
                ('origin_url', models.CharField(blank=True, max_length=1000)),
                ('prompt', models.TextField(blank=True)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('attribution', models.CharField(blank=True, max_length=500)),
                ('file', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('found_for_slug', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('origin_url', ''), _negated=True), fields=('origin_url',), name='uniq_imageasset_origin_url'), models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('content_hash',), name='uniq_imageasset_content_hash')],
            },
        ),
    ]
