# Generated by Django 5.1 on 2026-07-22 23:04

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_imageasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500)),
                ('source_cafe', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('imported', 'Imported'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('reference_price', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.imageasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
                ('source_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menuscan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
