# Generated by Django 5.1 on 2026-07-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_menuscan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='menu.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='raw_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='raw_price_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='raw_section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='source_page',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='split_from',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('merged', 'Merged'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuscan',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('failed', 'Failed')], default='queued', max_length=12),
        ),
    ]
