# Generated by Django 5.1 on 2026-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_universal_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuscan',
            name='image_task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
