# Generated by Django 5.1 on 2026-08-01 09:22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First: the GIN index below is created with `gin_trgm_ops`, which does
        # not exist until pg_trgm is installed.
        TrigramExtension(),
        migrations.AddField(
            model_name='item',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='origin_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='menu.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='search_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='shareable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('search_name'), name='gin_trgm_ops'), name='item_search_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['search_name', 'variant_label'], name='item_search_variant'),
        ),
    ]
