# Generated by Django 5.1 on 2026-08-01 09:23

import pgvector.django.vector
from django.db import migrations


def drop_dead_vectors(apps, schema_editor):
    """The stored vectors are Gemini's, in a space the new model does not share.
    Casting them would fail; keeping them would be worse -- they would rank."""
    apps.get_model('menu', 'Item').objects.update(embedding=None)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_item_library_fields'),
    ]

    operations = [
        migrations.RunPython(drop_dead_vectors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
