# Generated by Django 5.1 on 2026-08-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_item_embedding_1024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracting', 'Extracting'), ('gate1', 'Gate 1'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vision_model', models.CharField(blank=True, max_length=120)),
                ('embed_model', models.CharField(blank=True, max_length=120)),
                ('branches', models.ManyToManyField(related_name='menu_builds', to='menu.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_builds', to='menu.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuscan',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='menu.menubuild'),
        ),
        migrations.CreateModel(
            name='MenuBuildSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('icon_key', models.CharField(blank=True, max_length=60)),
                ('prices_confirmed', models.BooleanField(default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='menu.menubuild')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MenuBuildRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('base_name', models.CharField(blank=True, max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('raw_name', models.CharField(blank=True, max_length=300)),
                ('raw_price_text', models.CharField(blank=True, max_length=120)),
                ('split_from', models.CharField(blank=True, max_length=300)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(blank=True, max_length=20)),
                ('match_state', models.CharField(choices=[('none', 'No match'), ('auto', 'Auto'), ('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=10)),
                ('image_prompt', models.TextField(blank=True)),
                ('image_state', models.CharField(choices=[('none', 'None'), ('matched', 'From the library'), ('generated', 'Generated')], default='none', max_length=10)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='menu.menubuild')),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_rows', to='menu.imageasset')),
                ('matched_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_rows', to='menu.item')),
                ('published_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_rows', to='menu.menuitem')),
                ('source_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_rows', to='menu.menuscan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='menu.menubuildsection')),
            ],
            options={
                'ordering': ['section__display_order', 'display_order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='menubuildsection',
            constraint=models.UniqueConstraint(fields=('build', 'name'), name='uniq_buildsection_build_name'),
        ),
    ]
