# Generated by Django 5.1 on 2026-08-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_guestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.guestsession'),
        ),
    ]
