# Generated by Django 5.1 on 2026-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_order_guest_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='identity_mode',
            field=models.CharField(choices=[('auto', 'Guest A/B/C'), ('name', 'Name'), ('phone', 'Phone + OTP'), ('room', 'Room number')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='identity_skippable',
            field=models.BooleanField(default=True),
        ),
    ]
