# Generated by Django 5.1 on 2026-09-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_orderitem_note'),
        ('menu', '0025_otpchallenge'),
    ]

    operations = [
    ]
